use num_enum::{FromPrimitive, IntoPrimitive};

#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, IntoPrimitive, FromPrimitive)]
pub enum CommandId {
    GetControllerId = 0x19,
    // GetControllerStats = 0x80,
    // GetDPacStats = 0xA4,
    // GetTaskStats = 0x16,
    // ReadBPacIndex = 0x3D,
    // ReadBPacInteger = 0x3E,
    // ReadBPacLogic = 0xBC,
    // ReadBPacReal = 0xBF,
    ReadPartAttrHeader = 0xCB,
    ReadDPacPage = 0x10,
    ReadHuge = 0xD9,
    ReadIndex = 0xD6,
    ReadInteger = 0x57,
    ReadLogic = 0xD5,
    ReadReal = 0x58,
    ReadString = 0xDA,
    // ReadTaskIndex = 0x2C,
    // ReadTaskInteger = 0xAD,
    // ReadTaskLogic = 0xAB,
    // ReadTaskPage = 0x0D,
    // ReadTaskReal = 0xAE,
    // ReadText = 0x8A,
    // ReadVPacIndex = 0x07,
    // ReadVPacIndexSegmented = 0x34,
    // ReadVPacInteger = 0x08,
    // ReadVPacIntegerSegmented = 0xB5,
    // ReadVPacLogic = 0x86,
    // ReadVPacLogicSegmented = 0xB3,
    // ReadVPacReal = 0x89,
    // ReadVPacRealSegmented = 0xB6,
    // WriteBPacIndex = 0xB9,
    // WriteBPacInteger = 0xBA,
    // WriteBPacLogic = 0x38,
    // WriteBPacReal = 0x3B,
    WriteHuge = 0xD3,
    WriteIndex = 0xD0,
    WriteInteger = 0x51,
    WriteLogic = 0x4F,
    WriteReal = 0x52,
    WriteString = 0x54,
    // WriteTaskIndex = 0xA8,
    // WriteTaskInteger = 0x29,
    // WriteTaskLogic = 0xA7,
    // WriteTaskReal = 0x2A,
    // WriteText = 0x85,
    // WriteVPacIndex = 0x02,
    // WriteVPacIndexSegmented = 0xB0,
    // WriteVPacInteger = 0x83,
    // WriteVPacIntegerSegmented = 0x31,
    // WriteVPacLogic = 0x01,
    // WriteVPacLogicSegmented = 0x2F,
    // WriteVPacReal = 0x04,
    // WriteVPacRealSegmented = 0x32,
    #[num_enum(catch_all)]
    Unknown(u8),
}
